train:
  _target_: torchvision.transforms.Compose
  _recursive_: true
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.RandomCrop
      size: 224
    - _target_: torchvision.transforms.RandomHorizontalFlip
test:
  _target_: torchvision.transforms.Compose
  _recursive_: true
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Resize
      size: [224, 224]
