train:
  _target_: torchvision.transforms.Compose
  _recursive_: true
  transforms:
    - _target_: torchvision.transforms.RandAugment
      num_ops: 2
      magnitude: 9
    - _target_: torchvision.transforms.ColorJitter
      brightness: (0.6, 1.4)
      contrast: (0.6, 1.4)
      saturation: (0.6, 1.4)
      hue: 0
    - _target_: torchvision.transforms.Resize
      size: (248, 248)
      interpolation: torchvision.transforms.InterpolationMode.BICUBIC
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
test:
  _target_: torchvision.transforms.Compose
  _recursive_: true
  transforms:
    - _target_: torchvision.transforms.Resize
      size: (248, 248)
      interpolation: torchvision.transforms.InterpolationMode.BICUBIC
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
