Join_Patience:
  parameters:
    threshold: [0.5 , 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    alpha: [-1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  halting_mechanism:
    _target_: playground.halting.orto.OrtoHalting
    mode: higher
    accepted_thresholds: [ 0, 1 ]
    enable_halting: True
    scoring_function:
      _target_: hydra.utils.get_method
      path: playground.halting.utils.highest_probability
