gaussian_no_training_3_cnn:
  overwrite_evaluation: No
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  use_cnn_ae: Yes
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.5
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_025_3_cnn:
  splitting_point: 3
  use_cnn_ae: Yes
  overwrite_evaluation: No
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.25
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_01_3_cnn:
  splitting_point: 3
  unwrap_after: Yes
  use_cnn_ae: Yes
  overwrite_evaluation: No
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    dims: [-2, -1]
    snr: [ -100, 100 ]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.1
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_01_3_cnn_m20_p20:
  overwrite_evaluation: No
  use_cnn_ae: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.1
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_3_cnn_m20_p20:
  overwrite_evaluation: No
  use_cnn_ae: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.5
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_025_3_cnn_m20_p20:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.25
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_0001_3_cnn_m20_p20:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.001
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_0001_3_cnn:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.001
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_005_3_cnn_m20_p20:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.05
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_005_3_cnn:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.05
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_001_3_cnn_m20_p20:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.01
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_001_3_cnn:
  overwrite_evaluation: No
  use_cnn_ae: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.01
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_015_3_cnn_m20_p20:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    dims: [-2, -1]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.15
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_015_3_cnn:
  overwrite_evaluation: No
  splitting_point: 3
  use_cnn_ae: Yes
  unwrap_after: Yes
  unwrap_before: No
  epochs: 10
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20, 20 ]
    dims: [-2, -1]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.15
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
