gaussian_noise:
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 1.0
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training:
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -20 , 20 ]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 1.0
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
