gaussian_noise_3:
  overwrite_model: Yes
  overwrite_evaluation: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 25
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.5
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
#gaussian_noise_3_test:
#  overwrite_model: No
#  overwrite_evaluation: Yes
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 100
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -100, 100 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.5
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
gaussian_no_training_3:
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.5
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_025_3:
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.25
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_025_3:
  overwrite_model: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 50
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.25
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_no_training_01_3:
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: No
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.1
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
gaussian_noise_01_3:
  overwrite_model: Yes
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 50
  freeze_model: Yes
  channel:
    _target_: comm.channel.GaussianNoiseChannel
    snr: [ -100, 100 ]
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.1
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
