fading_noise_3_m20_p20:
  opt_index: 1
  overwrite_model: No
  splitting_point: 3
  unwrap_after: Yes
  unwrap_before: No
  epochs: 100
  freeze_model: Yes
  channel:
    _target_: comm.channel.FadingGaussianNoiseChannel
    snr: [ -20 , 50 ]
    fading_sigma: 1
    use_training_snr: Yes
  encoder:
    _target_: comm.pipeline.BaseRealToComplexNN
    output_size: 0.5
    n_layers: 3
    normalize: Yes
    drop_last_activation: Yes
  decoder:
    _target_: comm.pipeline.ConcatComplexToRealNN
    n_layers: 3
#fading_noise_025_3_m20_p20_2:
#  opt_index: 1
#  overwrite_model: No
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 50
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.25
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
#fading_noise_3:
#  overwrite_model: No
#  overwrite_evaluation: No
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -100, 100 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.5
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_3:
##  opt_index: 2
##  overwrite_model: no
##  overwrite_evaluation: No
##  splitting_point: 3
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 100
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -100, 100 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.5
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
##fading_no_training_025_3:
##  opt_index: 2
##  splitting_point: 3
##  overwrite_evaluation: No
##  overwrite_model: No
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 100
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -100, 100 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.25
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
#fading_noise_025_3:
#  overwrite_model: No
#  overwrite_evaluation: No
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 50
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -100, 100 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.25
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_01_3:
##  opt_index: 2
##  splitting_point: 3
##  overwrite_evaluation: No
##  unwrap_after: Yes
##  overwrite_model: No
##  unwrap_before: No
##  epochs: 100
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -100, 100 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.1
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
#fading_noise_01_3:
#  overwrite_model: No
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 50
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -100, 100 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.1
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
#fading_noise_01_3_m20_p20:
#  overwrite_model: No
#  opt_index: 1
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20, 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.1
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
#fading_noise_3_m20_p20:
#  overwrite_model: No
#  overwrite_evaluation: No
#  opt_index: 1
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.5
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
#fading_noise_025_3_m20_p20:
#  overwrite_model: No
#  splitting_point: 3
#  opt_index: 1
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.25
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
#fading_noise_0001_3_m20_p20:
#  overwrite_model: No
#  opt_index: 1
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.001
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_0001_3:
##  overwrite_model: No
##  overwrite_evaluation: No
##  opt_index: 2
##  splitting_point: 3
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 25
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -20, 20 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.001
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
#fading_noise_005_3_m20_p20:
#  overwrite_model: No
#  opt_index: 1
#  splitting_point: 3
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.05
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_005_3:
##  overwrite_model: No
##  opt_index: 2
##  overwrite_evaluation: No
##  splitting_point: 3
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 25
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -20, 20 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.05
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
#fading_noise_001_3_m20_p20:
#  overwrite_model: No
#  splitting_point: 3
#  opt_index: 1
#  unwrap_after: Yes
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.01
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_001_3:
##  overwrite_model: No
##  overwrite_evaluation: No
##  opt_index: 2
##  splitting_point: 3
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 25
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -20, 20 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.01
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
#fading_noise_015_3_m20_p20:
#  overwrite_model: No
#  splitting_point: 3
#  unwrap_after: Yes
#  opt_index: 1
#  unwrap_before: No
#  epochs: 25
#  freeze_model: Yes
#  channel:
#    _target_: comm.channel.GaussianNoiseChannel
#    snr: [ -20 , 20 ]
#    use_training_snr: Yes
#  encoder:
#    _target_: comm.pipeline.BaseRealToComplexNN
#    output_size: 0.15
#    n_layers: 3
#    normalize: Yes
#    drop_last_activation: Yes
#  decoder:
#    _target_: comm.pipeline.ConcatComplexToRealNN
#    n_layers: 3
##fading_no_training_015_3:
##  overwrite_model: No
##  overwrite_evaluation: No
##  opt_index: 2
##  splitting_point: 3
##  unwrap_after: Yes
##  unwrap_before: No
##  epochs: 25
##  freeze_model: Yes
##  channel:
##    _target_: comm.channel.GaussianNoiseChannel
##    snr: [ -20, 20 ]
##    use_training_snr: No
##  encoder:
##    _target_: comm.pipeline.BaseRealToComplexNN
##    output_size: 0.15
##    n_layers: 3
##    normalize: Yes
##    drop_last_activation: Yes
##  decoder:
##    _target_: comm.pipeline.ConcatComplexToRealNN
##    n_layers: 3
