train:
  _target_: torchvision.datasets.SVHN
  train: Yes
#  transform: ${training_pipeline.augmentations.train}
  transform: ${training_pipeline.augmentation.train}
  root: ${core.dataset_root}/svhn
  download: Yes
test:
  _target_: torchvision.datasets.SVHN
  train: No
  transform: ${training_pipeline.augmentation.test}
  root: ${core.dataset_root}/svhn
  download: Yes