optimizer:
  _target_: torch.optim.SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0
dataset:
  train:
    _target_: torchvision.datasets.CIFAR10
    train: Yes
    transform:
      _target_: torchvision.transforms.Compose
      _recursive_: true
      transforms:
        - _target_: torchvision.transforms.RandomCrop
          size: 32
          padding: 4
        - _target_: torchvision.transforms.RandomHorizontalFlip
        - _target_: torchvision.transforms.ToTensor
    root: ${core.dataset_root}/cifar10
    download: Yes
  test:
    _target_: torchvision.datasets.CIFAR10
    train: No
    transform:
      _target_: torchvision.transforms.Compose
      _recursive_: true
      transforms:
        - _target_: torchvision.transforms.ToTensor
    root: ${core.dataset_root}/cifar10
    download: Yes
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  shuffle: true
  sampler: null
  num_workers: 0
  collate_fn: null
  pin_memory: null
  drop_last: no
schema:
  epochs: 60
  dev_split: 0.1
  train_batch_size: 32
  eval_batch_size: 128
early_stopping:
  _target_: base.utils.EarlyStopper
  patience: 10
  min_delta: 0
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${pretraining_pipeline.schema.epochs}